# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import motion_server_pb2 as motion__server__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in motion_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotionServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMotion = channel.unary_unary(
                '/motion_server.MotionServerService/SetMotion',
                request_serializer=motion__server__pb2.SetMotionRequest.SerializeToString,
                response_deserializer=motion__server__pb2.SetMotionReply.FromString,
                _registered_method=True)
        self.ClearMotion = channel.unary_unary(
                '/motion_server.MotionServerService/ClearMotion',
                request_serializer=motion__server__pb2.ClearMotionRequest.SerializeToString,
                response_deserializer=motion__server__pb2.ClearMotionReply.FromString,
                _registered_method=True)
        self.StopRepeat = channel.unary_unary(
                '/motion_server.MotionServerService/StopRepeat',
                request_serializer=motion__server__pb2.StopRepeatRequest.SerializeToString,
                response_deserializer=motion__server__pb2.StopRepeatReply.FromString,
                _registered_method=True)
        self.SetWait = channel.unary_unary(
                '/motion_server.MotionServerService/SetWait',
                request_serializer=motion__server__pb2.SetWaitRequest.SerializeToString,
                response_deserializer=motion__server__pb2.SetWaitReply.FromString,
                _registered_method=True)
        self.SetPos = channel.unary_unary(
                '/motion_server.MotionServerService/SetPos',
                request_serializer=motion__server__pb2.SetPosRequest.SerializeToString,
                response_deserializer=motion__server__pb2.SetPosReply.FromString,
                _registered_method=True)
        self.SetVel = channel.unary_unary(
                '/motion_server.MotionServerService/SetVel',
                request_serializer=motion__server__pb2.SetVelRequest.SerializeToString,
                response_deserializer=motion__server__pb2.SetVelReply.FromString,
                _registered_method=True)
        self.SetAcc = channel.unary_unary(
                '/motion_server.MotionServerService/SetAcc',
                request_serializer=motion__server__pb2.SetAccRequest.SerializeToString,
                response_deserializer=motion__server__pb2.SetAccReply.FromString,
                _registered_method=True)


class MotionServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRepeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAcc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotion,
                    request_deserializer=motion__server__pb2.SetMotionRequest.FromString,
                    response_serializer=motion__server__pb2.SetMotionReply.SerializeToString,
            ),
            'ClearMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearMotion,
                    request_deserializer=motion__server__pb2.ClearMotionRequest.FromString,
                    response_serializer=motion__server__pb2.ClearMotionReply.SerializeToString,
            ),
            'StopRepeat': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRepeat,
                    request_deserializer=motion__server__pb2.StopRepeatRequest.FromString,
                    response_serializer=motion__server__pb2.StopRepeatReply.SerializeToString,
            ),
            'SetWait': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWait,
                    request_deserializer=motion__server__pb2.SetWaitRequest.FromString,
                    response_serializer=motion__server__pb2.SetWaitReply.SerializeToString,
            ),
            'SetPos': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPos,
                    request_deserializer=motion__server__pb2.SetPosRequest.FromString,
                    response_serializer=motion__server__pb2.SetPosReply.SerializeToString,
            ),
            'SetVel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVel,
                    request_deserializer=motion__server__pb2.SetVelRequest.FromString,
                    response_serializer=motion__server__pb2.SetVelReply.SerializeToString,
            ),
            'SetAcc': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAcc,
                    request_deserializer=motion__server__pb2.SetAccRequest.FromString,
                    response_serializer=motion__server__pb2.SetAccReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motion_server.MotionServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motion_server.MotionServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/SetMotion',
            motion__server__pb2.SetMotionRequest.SerializeToString,
            motion__server__pb2.SetMotionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/ClearMotion',
            motion__server__pb2.ClearMotionRequest.SerializeToString,
            motion__server__pb2.ClearMotionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRepeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/StopRepeat',
            motion__server__pb2.StopRepeatRequest.SerializeToString,
            motion__server__pb2.StopRepeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/SetWait',
            motion__server__pb2.SetWaitRequest.SerializeToString,
            motion__server__pb2.SetWaitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/SetPos',
            motion__server__pb2.SetPosRequest.SerializeToString,
            motion__server__pb2.SetPosReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/SetVel',
            motion__server__pb2.SetVelRequest.SerializeToString,
            motion__server__pb2.SetVelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAcc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion_server.MotionServerService/SetAcc',
            motion__server__pb2.SetAccRequest.SerializeToString,
            motion__server__pb2.SetAccReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
